// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag at
// 2019-09-19 08:40:10.0475998 +0200 SAST m=+0.034072301

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "license": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/metrics": {
            "get": {
                "description": "Returns a JSON object containing all metrics for CPU, Memory, and Disk",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "metrics"
                ],
                "summary": "Get all metrics",
                "responses": {
                    "200": {
                        "description": "JSON object containing all the metrics",
                        "schema": {
                            "$ref": "#/definitions/collector.Metrics"
                        }
                    }
                }
            }
        },
        "/api/metrics/cpu": {
            "get": {
                "description": "Returns a JSON object containing all CPU metrics",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "metrics"
                ],
                "summary": "Get CPU metrics",
                "responses": {
                    "200": {
                        "description": "JSON object containing CPU metrics",
                        "schema": {
                            "$ref": "#/definitions/collector.CPUMetrics"
                        }
                    }
                }
            }
        },
        "/api/metrics/disks": {
            "get": {
                "description": "Returns a JSON object containing all disk metrics",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "metrics"
                ],
                "summary": "Get disk metrics",
                "responses": {
                    "200": {
                        "description": "JSON array containing disk metrics",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/collector.DiskMetrics"
                            }
                        }
                    }
                }
            }
        },
        "/api/metrics/load": {
            "get": {
                "description": "Returns a JSON object containing all load metrics",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "metrics"
                ],
                "summary": "Get load metrics",
                "responses": {
                    "200": {
                        "description": "JSON object containing load metrics",
                        "schema": {
                            "$ref": "#/definitions/collector.LoadMetrics"
                        }
                    }
                }
            }
        },
        "/api/metrics/memory": {
            "get": {
                "description": "Returns a JSON object containing all memory metrics",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "metrics"
                ],
                "summary": "Get CPU metrics",
                "responses": {
                    "200": {
                        "description": "JSON object containing memory metrics",
                        "schema": {
                            "$ref": "#/definitions/collector.MemoryMetrics"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "collector.CPUMetrics": {
            "type": "object",
            "properties": {
                "idle": {
                    "type": "number"
                },
                "perc": {
                    "type": "number"
                },
                "system": {
                    "type": "number"
                },
                "user": {
                    "type": "number"
                }
            }
        },
        "collector.DiskMetrics": {
            "type": "object",
            "properties": {
                "free": {
                    "type": "string"
                },
                "mount": {
                    "type": "string"
                },
                "perc": {
                    "type": "number"
                },
                "used": {
                    "type": "string"
                }
            }
        },
        "collector.LoadMetrics": {
            "type": "object",
            "properties": {
                "load_1": {
                    "type": "number"
                },
                "load_15": {
                    "type": "number"
                },
                "load_5": {
                    "type": "number"
                }
            }
        },
        "collector.MemoryMetrics": {
            "type": "object",
            "properties": {
                "free": {
                    "type": "string"
                },
                "perc": {
                    "type": "number"
                },
                "total": {
                    "type": "string"
                },
                "used": {
                    "type": "string"
                }
            }
        },
        "collector.Metrics": {
            "type": "object",
            "properties": {
                "cpu": {
                    "type": "object",
                    "$ref": "#/definitions/collector.CPUMetrics"
                },
                "disks": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/collector.DiskMetrics"
                    }
                },
                "load": {
                    "type": "object",
                    "$ref": "#/definitions/collector.LoadMetrics"
                },
                "memory": {
                    "type": "object",
                    "$ref": "#/definitions/collector.MemoryMetrics"
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "1.0",
	Host:        "",
	BasePath:    "",
	Schemes:     []string{},
	Title:       "Eye of Sauron API",
	Description: "",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
